#!/usr/bin/env bash
set -euxo pipefail

CONFIG_DIR=~/.config
BREW_PACKAGES=("delta" "neovim" "bat" "lazygit" "bat" "z" "luarocks" "antigen" "pure" "fd" "gnupg" "gh" "git")

echo "Creating config directory"
mkdir -p $CONFIG_DIR

for d in */ ; do
  echo "Linking directory $d"
  ln -sf $(pwd)/${d%/} $CONFIG_DIR/${d%/}
done

if ! command -v brew 2>&1 >/dev/null
then
  echo "Homebrew doesn't appear to be installed!"
  exit 1
fi

brew update && brew install ${BREW_PACKAGES[@]}

echo "Configuring ohmyzsh (extending zshrc). Make sure you've installed ohmyzsh."
echo "source $CONFIG_DIR/zsh/.zshrc-base" >> ~/.zshrc
echo "source $CONFIG_DIR/zsh/.antigen" >> ~/.zshrc
